Start
Vadim692001/FoodDelivery pull request #1
Opened 2021-04-11 08:19 UTC by Vadim692001

My test
Homwork

2021-04-12 07:10 UTC, serhii-shkodenko requested changes
Виконання завдання потребує суттєвого поліпшення.

2021-04-12 07:10 UTC, serhii-shkodenko commented on Data.cs
> +            //int waynesreet = destinations.TakeWhile(destinations =>! destinations.Contains("North Heather Street")).Count();
Заоментований код краще не включати у ПР. Загалом практика така, що його на продакшені не має бути такого коду.

2021-04-12 07:10 UTC, serhii-shkodenko commented on Data.cs
> +            if ((price.Length == destination.Length) == (client.Length == currencie.Length))
Щоб уникнути того, що основний код, який обчислює вартість доставки, знаходиться у середні блоку `if`, краще зробити так:
```
if(![умови, які перевіряються])
{
    else { Console.WriteLine("Дані не коректні"); }
}
[основний код]
```

2021-04-12 07:10 UTC, serhii-shkodenko commented on Data.cs
> +                var deliveryForXavierBowers = (price[4] - 31.25m);
Тут треба закодувати такий алгоритм, який буде виконуватися, незалежно від значення індексів. А зараз виходить, що твій код буде працювати лише для одного конкретного випадку. Це треба переробити.

2021-04-14 12:47 UTC, serhii-shkodenko requested changes
Потрібне суттєве оновлення логіки. Поправте, будь ласка.

2021-04-14 12:47 UTC, serhii-shkodenko commented on Data.cs
> +            var price = prices.ToArray();
Змінна зберігає колекцію об'єктів, а для її назви використаний іменник в однині. Має бути в множині.

2021-04-14 12:47 UTC, serhii-shkodenko commented on Data.cs
> +            var destination = destinations.ToArray();
Змінна зберігає колекцію об'єктів, а для її назви використаний іменник в однині. Має бути в множині.

2021-04-14 12:47 UTC, serhii-shkodenko commented on Data.cs
> +            var client = clients.ToArray();
Змінна зберігає колекцію об'єктів, а для її назви використаний іменник в однині. Має бути в множині.

2021-04-14 12:47 UTC, serhii-shkodenko commented on Data.cs
> +            var currencie = currencies.ToArray();
Змінна зберігає колекцію об'єктів, а для її назви використаний іменник в однині. Має бути в множині.

2021-04-14 12:47 UTC, serhii-shkodenko commented on Data.cs
> +                if ((client[i] == "Sariah Bennett" && client[i -1] == "Amiah Simmons" || client[i] == "Amiah Simmons" && client[i-1] == "Sariah Bennett"))
Некоректна логіка. Код має сам визначити, який з елементів в колекції відноситься до дітей, фактично тут просто хардкод, який буде правильно працювати лише для одного випадку.

2021-04-14 12:47 UTC, serhii-shkodenko commented on Data.cs
> +                switch (client[i])
Некоректна логіка. По-перше, тут захардкожені значення колекції, якій в реальності будут завжди приходити нові. По-друге, чомусь дисконт, пов'язаний з вулицею, обчислюється в залежності від імені клієнта.

2021-04-16 18:08 UTC, serhii-shkodenko requested changes
Будь-ласка, виправте ці зауваження.

2021-04-16 18:08 UTC, serhii-shkodenko commented on Data.cs
> +       private const string wayneStreet = "Wayne Street";
Константи у C# називаються у `PascalCase`.

2021-04-16 18:08 UTC, serhii-shkodenko commented on Data.cs
> +        private const string northHeatherStreet = "North Heather Street";
Константи у C# називаються у `PascalCase`.

2021-04-16 18:08 UTC, serhii-shkodenko commented on Data.cs
> +        private const decimal discountChildrens = 0.75m;
Константи у C# називаються у `PascalCase`.

2021-04-16 18:08 UTC, serhii-shkodenko commented on Data.cs
> +        private const decimal discountInfants = 0.5m;
Константи у C# називаються у `PascalCase`.

2021-04-16 18:08 UTC, serhii-shkodenko commented on Data.cs
> +        private const decimal neighborDiscount = 0.85m;
Константи у C# називаються у `PascalCase`.

2021-04-16 18:08 UTC, serhii-shkodenko commented on Data.cs
> +        private  const decimal discountWayneStreet = 10;
Константи у C# називаються у `PascalCase`.

2021-04-16 18:08 UTC, serhii-shkodenko commented on Data.cs
> +        private const decimal discountNorthHeatherStreet = 5.36m;
Константи у C# називаються у `PascalCase`.

2021-04-16 18:08 UTC, serhii-shkodenko commented on Data.cs
> +        private const decimal euroExchange = 1.19m;
Константи у C# називаються у `PascalCase`.

2021-04-16 18:08 UTC, serhii-shkodenko commented on Data.cs
> +            foreach (var etem in clients) { Console.WriteLine($"Завмовники:\t{etem}"); }
Одрук, треба `item` замість `etem`.

2021-04-16 18:08 UTC, serhii-shkodenko commented on Data.cs
> +            foreach (var etem in destinations) { Console.WriteLine($"Адрес доставки:\t{etem}"); }
Одрук, треба `item` замість `etem`.

2021-04-16 18:08 UTC, serhii-shkodenko commented on Data.cs
> +            string pastaddres = default;
Змінні у C# йменуються в `camelCase`. Треба `pastAddress` (зверніть увагу на подвійну у `ss` кінці).

2021-04-16 18:08 UTC, serhii-shkodenko commented on Data.cs
> +            decimal sumPrice = default;
Ця змінна насправді тут непотрібна. Ви важе маєте змінну `fullPrice`, у ній також можна зберігати проміжний результат, як зараз ви робите із `sumPrice`.

2021-04-16 18:57 UTC, Vadim692001 commented on Data.cs
> +            decimal sumPrice = default;
Так тоді я не зможу вивести загальну суму  доставки, будуть тільки суми доставки їжі під конкретну ітерацію

2021-04-16 20:00 UTC, serhii-shkodenko commented on Data.cs
> +            decimal sumPrice = default;
Згода. Тоді змінну краще назвати по-іншому, щоб у назві не було слова `sum`, можливо `orderPrice`.

2021-04-17 21:18 UTC, serhii-shkodenko approved these changes
Виглядає добре. Можна мержити.

2021-04-18 13:08 UTC, merged